# Generated by Django 6.0.6 on 2026-07-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_knowledgeentry_quality_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeentry',
            name='quality_status',
            field=models.CharField(choices=[('strong', 'Kuat'), ('needs_review', 'Perlu ditinjau'), ('weak', 'Lemah')], default='needs_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='source_type',
            field=models.CharField(choices=[('faq', 'FAQ'), ('product', 'Produk'), ('sop', 'SOP'), ('article', 'Artikel')], default='faq', max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draf'), ('published', 'Terbit')], default='published', max_length=20),
        ),
    ]
