# Generated by Django 6.0.6 on 2026-07-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_default_login_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('ai_trainer', 'Pelatih AI'), ('customer', 'Pengguna')], default='customer', max_length=20),
        ),
    ]
