# Generated by Django 6.0.6 on 2026-07-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationmessage',
            name='response_state',
            field=models.CharField(choices=[('answered', 'Answered'), ('fallback', 'Fallback')], default='answered', max_length=20),
        ),
        migrations.AddField(
            model_name='consultationmessage',
            name='source_summary',
            field=models.TextField(blank=True),
        ),
    ]
