# Generated by Django 6.0.6 on 2026-07-12 14:42

import django.db.models.deletion
from django.db import migrations, models


def backfill_message_product(apps, schema_editor):
    ConsultationMessage = apps.get_model('consultations', 'ConsultationMessage')
    for message in ConsultationMessage.objects.select_related('session').all():
        if message.product_id or not message.session_id:
            continue
        session_product_id = getattr(message.session, 'product_id', None)
        if not session_product_id:
            continue
        message.product_id = session_product_id
        message.save(update_fields=['product'])


def clear_message_product(apps, schema_editor):
    ConsultationMessage = apps.get_model('consultations', 'ConsultationMessage')
    ConsultationMessage.objects.update(product_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('consultations', '0004_session_product_unanswered_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationmessage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_messages', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='airesponsereview',
            name='verdict',
            field=models.CharField(choices=[('accurate', 'Akurat'), ('needs_revision', 'Perlu revisi'), ('incorrect', 'Tidak tepat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='consultationmessage',
            name='response_state',
            field=models.CharField(choices=[('answered', 'Terjawab'), ('fallback', 'Cadangan')], default='answered', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultationmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'Pengguna'), ('ai', 'AI')], max_length=10),
        ),
        migrations.AlterField(
            model_name='consultationsession',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('closed', 'Ditutup')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='unansweredquestion',
            name='status',
            field=models.CharField(choices=[('open', 'Terbuka'), ('reviewed', 'Sudah ditinjau'), ('resolved', 'Selesai')], default='open', max_length=20),
        ),
        migrations.RunPython(backfill_message_product, clear_message_product),
    ]
